/* after changing this file run 'npm run webpack:build' */
/* tslint:disable */
import '../content/scss/vendor.scss';

// Imports all fontawesome core and solid icons

import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faUser,
    faSort,
    faSortUp,
    faSortDown,
    faSync,
    faEye,
    faBan,
    faTimes,
    faArrowLeft,
    faSave,
    faPlus,
    faPencilAlt,
    faBars,
    faThList,
    faUserPlus,
    faRoad,
    faTachometerAlt,
    faHeart,
    faList,
    faBell,
    faBook,
    faHdd,
    faFlag,
    faWrench,
    faClock,
    faCloud,
    faSignOutAlt,
    faSignInAlt,
    faCalendarAlt,
    faSearch,
    faTrashAlt,
    faAsterisk,
    faTasks,
    faHome,
    faInfo,
    faInfoCircle,
    faBlog,
    faCheckSquare,
    faEdit,
    faMailBulk,
    faHandHoldingHeart,
    faHandHolding,
    faHandshake,
    faHandsHelping,
    faHandHoldingUsd,
    faHammer,
    faHandPaper,
    faHandPeace,
    faHandPointer,
    faHands,
    faFistRaised,
    faAt,
    faImage,
    faImages,
    faBriefcase,
    faGavel,
    faCheckCircle,
    faGlobe,
    faCog,
    faCogs,
    faTools,
    faToolbox,
    faUserCog,
    faUsersCog,
    faHandScissors,
    faHandSpock,
    faPrayingHands,
    faArrowRight
} from '@fortawesome/free-solid-svg-icons';

// Adds the SVG icon to the library so you can use it in your page
library.add(faUser);
library.add(faSort);
library.add(faSortUp);
library.add(faSortDown);
library.add(faSync);
library.add(faEye);
library.add(faBan);
library.add(faTimes);
library.add(faArrowLeft);
library.add(faSave);
library.add(faPlus);
library.add(faPencilAlt);
library.add(faBars);
library.add(faHome);
library.add(faThList);
library.add(faUserPlus);
library.add(faRoad);
library.add(faTachometerAlt);
library.add(faHeart);
library.add(faList);
library.add(faBell);
library.add(faTasks);
library.add(faBook);
library.add(faHdd);
library.add(faFlag);
library.add(faWrench);
library.add(faClock);
library.add(faCloud);
library.add(faSignOutAlt);
library.add(faSignInAlt);
library.add(faCalendarAlt);
library.add(faSearch);
library.add(faTrashAlt);
library.add(faAsterisk);
library.add(faInfo);
library.add(faInfoCircle);
library.add(faBlog);
library.add(faCheckSquare);
library.add(faEdit);
library.add(faMailBulk);
library.add(faHands);
library.add(faHammer);
library.add(faHandHolding);
library.add(faHandHoldingHeart);
library.add(faHandHoldingUsd);
library.add(faHandPaper);
library.add(faHandPeace);
library.add(faHandshake);
library.add(faHandsHelping);
library.add(faFistRaised);
library.add(faAt);
library.add(faImage);
library.add(faImages);
library.add(faBriefcase);
library.add(faGavel);
library.add(faCheckCircle);
library.add(faGlobe);
library.add(faCog);
library.add(faCogs);
library.add(faTools);
library.add(faToolbox);
library.add(faUserCog);
library.add(faUsersCog);
library.add(faHandPointer);
library.add(faHandScissors);
library.add(faHandSpock);
library.add(faPrayingHands);
library.add(faArrowRight);
library.add(faBriefcase);
library.add(faFistRaised);
library.add(faFistRaised);
library.add(faToolbox);
// jhipster-needle-add-element-to-vendor - JHipster will add new menu items here
